### PR TITLE
Feature/glob-39502 Poco onboarding fe engineers - showcasing different sections of our FE dev tools and practices 

### PR DESCRIPTION
**Pull request by doron-globality**
**What is this PR?**

Poco is our new onboarding app for new FE engineers.
this PR encapsulates many changes/features that we added to this sample app: 

- showcasing the use of different gi-web-components
- showcasing the use of Sass
- showcasing the use of styled-components
- showcasing the use of our base app structure 
- showcasing the use of `ReactInt` internalization and string formatting tools.
- showcasing the use of Apollo GQL (still needs work)
- showcasing the use of uTest with snapshots

JIRA - https://globality.atlassian.net/browse/GLOB-39502

### CODE REVIEW

**Comment by cdm-ium** [comment]
i really want to know lint and tests exist/pass before merging. Can we make this repo private and add our internal scripts for building here? I would probably recommend doing that as a separate pr and then rebase this one on top of that.

**Comment by cdm-ium** [comment]
one way to move forward with this pr would be to strip it down to just the base app structure with a little localization logic in one pr.

then do another one with one or two gi-web components that you need to build the pizza app (without graphql)

then add graphql

etc.

**Comment by jameschung2019** [comment]
Hey there, please close this PR or merge it. It will be auto-closed in 48 hours if not acted upon. If you decide to merge it, comment and take ownership to coordinate, schedule, and get it done. Thanks!

**Comment by jameschung2019** [comment]
This PR is being closed per CTO leadership's decision.  All PRs older than 1/1/2020 is included.

**Pull request closed without merging**
